### ISSUE TITLE
Strings with leading zeroes don't always encode correctly

### ISSUE THREAD

**Issue by TvdW** [Sereal/Sereal#106]
perl -E'
      my $var= "012345";
      my $v2= $var+1;
      say $var;
      use Sereal;
      $var= decode_sereal(encode_sereal($var));
      say $var;
    '
    012345
    12345

Expected output:

    012345
    012345

**Comment by demerphq** [comment]
fixed in 3.005_005/3.006. Thanks for the  report/test case.
