### ISSUE TITLE
[PATCH] fix for POD error

### ISSUE THREAD

**Issue by gregoa** [Sereal/Sereal#112]
In Debian we are currently applying the following patch to
Sereal-Encoder.
We thought you might be interested in it too.

    Description: fix for POD error
        Around line 739:
            =back doesn't take any parameters, but you said =back 4
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2015-11-16
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libsereal-encoder-perl.git/plain/debian/patches/pod-syntax.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by dgryski** [comment]
Thanks!
