### ISSUE TITLE
Changing sort_keys/canonical representation.

### ISSUE THREAD

**Issue by demerphq** [Sereal/Sereal#113]
I really want to change the sort order in Sereal for sort_keys.

Currently we use reverse "alphabetical" order. (Not sure why reverse.)

The problem with this is that it is expensive to sort alphabetically between non-utf8 and utf8 data. sv_cmp() offers an API, but using it means that one has to convert all the keys to mortal SV's first, which is slow and memory costly. In the most recent production version of Sereal we do this for any hash with utf8 keys.

What I would like to do instead is sort keys by length ascending (making comparisons cheaper on average), and then "bytabetically" by their raw binary representation, and then by their utf8 flag. This means that the string "\xDF" would sort into two different positions in the hash depending on whether it was "utf8 on" or not. (We do the utf8 flag last because most times the flags wont matter. It will only come up if we store "\x{100}" and "\xC4\x80" in the same hash, which is quite unlikely.
 
So far I have heard from Avar and Steffen that they don't think it should be a problem to change the order. Anybody else have an opinion?

If necessary we can support a "sort_keys=>2" mode where it is alphabetical. (I would like the "fast" code to be default.)

**Comment by dgryski** [comment]
This will not be a problem for the Go implementation.

**Comment by jhi** [comment]
As a bonus you get to admonish people "I told you so" when their code exposes they were depending on the order.

**Comment by demerphq** [comment]
I am closing this as it was done long ago...
