### ISSUE TITLE
Missing parentheses in SRL_ENC_HAVE_OPTION() macro

### ISSUE THREAD

**Issue by ppisar** [Sereal/Sereal#116]
~~~~
From 38b829d8845fc795d9404cd0e24b21c5b06f0a6e Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Petr=20P=C3=ADsa=C5=99?= <ppisar@redhat.com>
Date: Fri, 27 Nov 2015 11:17:25 +0100
Subject: [PATCH] Add missing parentheses to SRL_ENC_HAVE_OPTION arguments
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

GCC warns about missing parentheses:

In file included from srl_encoder.c:50:0:
srl_encoder.c: In function ‘srl_dump_hv’:
srl_encoder.h:141:58: warning: suggest parentheses around arithmetic in operand of ‘|’ [-Wparentheses]
 #define SRL_ENC_HAVE_OPTION(enc, flag_num) ((enc)->flags & flag_num)
                                                          ^
srl_encoder.c:1431:18: note: in expansion of macro ‘SRL_ENC_HAVE_OPTION’
             if ( SRL_ENC_HAVE_OPTION(enc, SRL_F_SORT_KEYS|SRL_F_SORT_KEYS_PERL) ) {

And indeed this is a bug.

Signed-off-by: Petr Písař <ppisar@redhat.com>
---
 Perl/Encoder/srl_encoder.h | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/Perl/Encoder/srl_encoder.h b/Perl/Encoder/srl_encoder.h
index 12ca951..639f220 100644
--- a/Perl/Encoder/srl_encoder.h
+++ b/Perl/Encoder/srl_encoder.h
@@ -140,7 +140,7 @@ SV *srl_dump_data_structure_mortal_sv(pTHX_ srl_encoder_t *enc, SV *src, SV *use
 /* Set while the encoder is in active use / dirty */
 #define SRL_OF_ENCODER_DIRTY                 1UL
 
-#define SRL_ENC_HAVE_OPTION(enc, flag_num) ((enc)->flags & flag_num)
+#define SRL_ENC_HAVE_OPTION(enc, flag_num) ((enc)->flags & (flag_num))
 #define SRL_ENC_SET_OPTION(enc, flag_num) STMT_START {(enc)->flags |= (flag_num);}STMT_END
 #define SRL_ENC_RESET_OPTION(enc, flag_num) STMT_START {(enc)->flags &= ~(flag_num);}STMT_END
 
-- 
2.4.3

~~~~

**Comment by demerphq** [comment]
Thanks very much, patch is applied as cebb705b1487f5861416c7536bd57e3367b1fa8b

I will try to release 3.008 soon, maybe today.

**Comment by dgryski** [comment]
@demerphq Do we need to bump our gcc warning level and/or build with clang or something to catch stuff like this ourselves in the future?

**Comment by demerphq** [comment]
Good question. I dont know. Petr do you have an opinion?

Yves

On 27 November 2015 at 14:08, Damian Gryski <notifications@github.com>
wrote:

> @demerphq <https://github.com/demerphq> Do we need to bump our gcc
> warning level and/or build with clang or something to catch stuff like this
> ourselves in the future?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Sereal/Sereal/issues/116#issuecomment-160136202>.
>



-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by ppisar** [comment]
I built it with:

$ perl Makefile.PL INSTALLDIRS=vendor 'OPTIMIZE=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic'

Either it's caused by "-O2 -Wall" or by new enough GCC version (5.2.1).

-- Petr
