### ISSUE TITLE
Dependecies specification disappared from Sereal-Decoder-3.008's META files

### ISSUE THREAD

**Issue by ppisar** [Sereal/Sereal#117]
Sereal-Decoder-3.008 is missing dependency listing in META.json (prereqs) and META.yml (build_requires, configure_requires). They were there in 3.007.

**Comment by demerphq** [comment]
Bah.

I know why. I will fix it and release 3.009 now.

On 30 November 2015 at 10:24, Petr Pisar <notifications@github.com> wrote:

> Sereal-Decoder-3.008 is missing dependency listing in META.json (prereqs)
> and META.yml (build_requires, configure_requires). They were there in 3.007.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Sereal/Sereal/issues/117>.
>



-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by demerphq** [comment]
Pushed 3.009 to close this ticket.

On 30 November 2015 at 11:51, demerphq <demerphq@gmail.com> wrote:

> Bah.
>
> I know why. I will fix it and release 3.009 now.
>
> On 30 November 2015 at 10:24, Petr Pisar <notifications@github.com> wrote:
>
>> Sereal-Decoder-3.008 is missing dependency listing in META.json (prereqs)
>> and META.yml (build_requires, configure_requires). They were there in 3.007.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Sereal/Sereal/issues/117>.
>>
>
>
>
> --
> perl -Mre=debug -e "/just|another|perl|hacker/"
>



-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by demerphq** [comment]
Must remember to release using a modern perl. :-(
