### ISSUE TITLE
$in_source_repo Breaks Build

### ISSUE THREAD

**Issue by theory** [Sereal/Sereal#118]
When building with [git-build-rpm](https://github.com/iovation/git-build-rpm/), I get this error:

    failed to use blib: ../Encoder is not a directory

Looks like this is the culprit:

    my $in_source_repo = -d "../../.git" and -d $shared_dir;

Of course there is a `.git` directory in that location (and I expect a lot of folks would have one nearby). I don't have a shared directory, but the precedence isn't working the way you think. Change `and` to `&&` to fix it:

    my $in_source_repo = -d "../../.git" && -d $shared_dir;

**Comment by ikruglov** [comment]
Fixed. Thanks for reporting.

**Comment by demerphq** [comment]
We also got #119, and I did a more robust fix than just fixing the
precedence, although that probably was sufficient. I will release 3.010
soon.

On 30 November 2015 at 21:37, Ivan Kruglov <notifications@github.com> wrote:

> Closed #118 <https://github.com/Sereal/Sereal/issues/118>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Sereal/Sereal/issues/118#event-478186421>.
>



-- 
perl -Mre=debug -e "/just|another|perl|hacker/"
