### ISSUE TITLE
reflect: call of sereal.decodeHashViaReflection on interface Value

### ISSUE THREAD

**Issue by Oxygend** [Sereal/Sereal#123]
Trying to decode my very complicated structure I got the error "reflect: call of sereal.decodeHashViaReflection on interface Value"

My encoded file
[testImage.txt](https://github.com/Sereal/Sereal/files/67686/testImage.txt)

 Decoding function
```go
func LoadImage (file_name string) (*ExecutableImage, error) {
	file, err := os.Open(file_name)

	if err != nil {
		return nil, err
	}
	defer file.Close()

	stats, statsErr := file.Stat()
	if statsErr != nil {
		return nil, statsErr
	}

	var size int64 = stats.Size()
	bytes := make([]byte, size)

	bufr := bufio.NewReader(file)
	_, err = bufr.Read(bytes)
	if err != nil {
		return nil, err
	}

	dec := sereal.Decoder{}
	var img ExecutableImage
	err = dec.Unmarshal(bytes, &img)
	if err != nil {
		return nil, err
	}

	return &img, nil
}
```

Structure I'm trying to decode
```go
type ExecutableImage struct {
	VMVersion int
	LibSize int
	Libraries []string
	Functions []ImageFunction
	GlobalVariables []*ImageVariable
	EntryPoint *ImageFunction
}
```

I cannot provide the whole code because it's too big. The one thing I can say in addition is that cyclic and recursive pointers are being used in this structure.

**Comment by Oxygend** [comment]
The file I'm trying to decode
[testImage.txt](https://github.com/Sereal/Sereal/files/67685/testImage.txt)

**Comment by dgryski** [comment]
I'll take a look at this on Monday.

**Comment by dgryski** [comment]
Please let me know if this fixes your issue.  I can now successfully decode your test file.

**Comment by Oxygend** [comment]
I tested this out. Now I'm getting "panic: interface conversion: interface is map[string]interface {}, not Quad.Expression". 
I serialize the structure, and then, after deserialization, I try to access some of the fields and I got this.
So instead of type "Expression" interface was converted to "map[string]interface" during the deserialization

**Comment by dgryski** [comment]
I think in order to properly fix this, I would need at least the type definitions of the other structures involved in this.  As it stands, I can only deserialize this into the generic types and not into a proper typed struct.  You can email me at the address on my profile.
