### ISSUE TITLE
Bug. Segmentation Fault in perl Sereal::Encoder

### ISSUE THREAD

**Issue by nloginoff** [Sereal/Sereal#128]
Try this small example for see Bug.

`#!/usr/bin/perl

use strict;
use warnings;

use Sereal; # v 3.014

my $srl_encoder = Sereal::Encoder->new({no_shared_hashkeys => 1});

my @login;
$login[1] = 1;
$#login; # This line Make Segmentation Fault Error in Encode. Comment this line for normal Encode

warn "Start";
my $str = $srl_encoder->encode(\@login);	
warn "End";

exit;
`

**Comment by nloginoff** [comment]
`my @login;
$login[0] = 1;
$login[3] = 1;
$#login; # This line Make Segmentation Fault Error in Encode. Comment this line for normal Encode`

**Comment by demerphq** [comment]
On 4 April 2016 at 17:02, nloginoff <notifications@github.com> wrote:

> Try this small example for see Bug.
>
> `#!/usr/bin/perl
>
> use strict;
> use warnings;
>
> use Sereal; # v 3.014
>
> my $srl_encoder = Sereal::Encoder->new({no_shared_hashkeys => 1});
>
> my @login;
> $login[1] = 1;
> $#login; # This line Make Segmentation Fault Error in Encode. Comment this
> line for normal Encode
>
> warn "Start";
> my $str = $srl_encoder->encode(\@login);
>
> warn "End";
>
> exit;
> `
>
>
>
I cannot replicate. Can you please show me the output of perl -V, and also
could you add:

use Devel::Peek;
Dump(\@login);

to your code *before* the call to Sereal, and post the results.

Thanks,
Yves

**Comment by demerphq** [comment]
FWIW, I suspect this is a bug in Perl and not in Sereal. But please let me know the results of the code change I mentioned above.

**Comment by nloginoff** [comment]
Summary of my perl5 (revision 5 version 10 subversion 1) configuration:

  Platform:
    osname=linux, osvers=2.6.32-220.el6.x86_64, archname=x86_64-linux-thread-multi
    uname='linux c6b8.bsys.dev.centos.org 2.6.32-220.el6.x86_64 #1 smp tue dec 6 19:48:22 gmt 2011 x86_64 x86_64 x86_64 gnulinux '
    config_args='-des -Doptimize=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -DDEBUGGING=-g -Dversion=5.10.1 -Dmyhostname=localhost -Dperladmin=root@localhost -Dcc=gcc -Dcf_by=Red Hat, Inc. -Dprefix=/usr -Dvendorprefix=/usr -Dsiteprefix=/usr/local -Dsitelib=/usr/local/share/perl5 -Dsitearch=/usr/local/lib64/perl5 -Dprivlib=/usr/share/perl5 -Darchlib=/usr/lib64/perl5 -Dvendorlib=/usr/share/perl5/vendor_perl -Dvendorarch=/usr/lib64/perl5/vendor_perl -Dinc_version_list=5.10.0 -Darchname=x86_64-linux-thread-multi -Dlibpth=/usr/local/lib64 /lib64 /usr/lib64 -Duseshrplib -Dusethreads -Duseithreads -Duselargefiles -Dd_dosuid -Dd_semctl_semun -Di_db -Ui_ndbm -Di_gdbm -Di_shadow -Di_syslog -Dman3ext=3pm -Duseperlio -Dinstallusrbinperl=n -Ubincompat5005 -Uversiononly -Dpager=/usr/bin/less -isr -Dd_gethostent_r_proto -Ud_endhostent_r_proto -Ud_sethostent_r_proto -Ud_endprotoent_r_proto -Ud_setprotoent_r_proto -Ud_endservent_r_proto -Ud_setservent_r_proto -Dscriptdir=/usr/bin -Dusesitecustomize'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.4.7 20120313 (Red Hat 4.4.7-16)', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -fstack-protector'
    libpth=/usr/local/lib64 /lib64 /usr/lib64
    libs=-lresolv -lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lpthread -lc
    perllibs=-lresolv -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
    libc=, so=so, useshrplib=true, libperl=libperl.so
    gnulibc_version='2.12'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE'
    cccdlflags='-fPIC', lddlflags='-shared -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic'


Characteristics of this binary (from libperl):
  Compile-time options: MULTIPLICITY PERL_DONT_CREATE_GVSV
                        PERL_IMPLICIT_CONTEXT PERL_MALLOC_WRAP USE_64_BIT_ALL
                        USE_64_BIT_INT USE_ITHREADS USE_LARGE_FILES
                        USE_PERLIO USE_REENTRANT_API USE_SITECUSTOMIZE
  Built under linux
  Compiled at Nov 10 2015 12:05:27
  %ENV:
    PERL5LIB="/home/stork/sites/combats.ru/lib:/home/stork/sites/combats.ru/web:/home/stork/sites/combats.ru/libold"
  @INC:
    /home/stork/sites/combats.ru/lib
    /home/stork/sites/combats.ru/web
    /home/stork/sites/combats.ru/libold
    /usr/local/lib64/perl5
    /usr/local/share/perl5
    /usr/lib64/perl5/vendor_perl
    /usr/share/perl5/vendor_perl
    /usr/lib64/perl5
    /usr/share/perl5
    .

**Comment by nloginoff** [comment]
#!/usr/bin/perl

use strict;
use warnings;

use Sereal; # v 3.014

my $srl_encoder = Sereal::Encoder->new({no_shared_hashkeys => 1});

my @login;
$login[0] = 1;
$login[3] = 1;
$#login; # This line Make Segmentation Fault Error in Encode. Comment this line for normal Encode

use Devel::Peek;
Dump(\@login);


Useless use of array length in void context at ./ser_test.pl line 13.
SV = RV(0xb68260) at 0xb68250
  REFCNT = 1
  FLAGS = (TEMP,ROK)
  RV = 0xb68298
  SV = PVAV(0xb4cbf8) at 0xb68298
    REFCNT = 2
    FLAGS = (PADMY,RMG)
    MAGIC = 0xb86fe0
      MG_VIRTUAL = &PL_vtbl_arylen_p
      MG_TYPE = PERL_MAGIC_arylen_p(@)
      MG_FLAGS = 0x02
        REFCOUNTED
      MG_OBJ = 0xb4bf88
      SV = PVMG(0xc0fa10) at 0xb4bf88
        REFCNT = 1
        FLAGS = (GMG,SMG)
        IV = 0
        NV = 0
        PV = 0
        MAGIC = 0xc22990
          MG_VIRTUAL = &PL_vtbl_arylen
          MG_TYPE = PERL_MAGIC_arylen(#)
          MG_OBJ = 0xb68298
    ARRAY = 0xba6700
    FILL = 3
    MAX = 3
    ARYLEN = 0xb4bf88
    FLAGS = (REAL)
    Elt No. 0
    SV = IV(0xb84550) at 0xb84558
      REFCNT = 1
      FLAGS = (IOK,pIOK)
      IV = 1
    Elt No. 1
    Elt No. 2
    Elt No. 3
    SV = IV(0xb4bd40) at 0xb4bd48
      REFCNT = 1
      FLAGS = (IOK,pIOK)
      IV = 1
Start at ./ser_test.pl line 18.
Ошибка сегментирования

**Comment by demerphq** [comment]
Perl 5.10 is very old, and I suspect this bug in 5.10 specific. I dont see
anything  that would suggest this is Sereal's fault.

Yves

On 4 April 2016 at 18:00, nloginoff <notifications@github.com> wrote:

> #!/usr/bin/perl
>
> use strict;
> use warnings;
>
> use Sereal; # v 3.014
>
> my $srl_encoder = Sereal::Encoder->new({no_shared_hashkeys => 1});
>
> my @login;
> $login[0] = 1;
> $login[3] = 1;
> $#login; # This line Make Segmentation Fault Error in Encode. Comment this
> line for normal Encode
>
> use Devel::Peek;
> Dump(\@login);
>
> Useless use of array length in void context at ./ser_test.pl line 13.
> SV = RV(0xb68260) at 0xb68250
> REFCNT = 1
> FLAGS = (TEMP,ROK)
> RV = 0xb68298
> SV = PVAV(0xb4cbf8) at 0xb68298
> REFCNT = 2
> FLAGS = (PADMY,RMG)
> MAGIC = 0xb86fe0
> MG_VIRTUAL = &PL_vtbl_arylen_p
> MG_TYPE = PERL_MAGIC_arylen_p(@)
> MG_FLAGS = 0x02
> REFCOUNTED
> MG_OBJ = 0xb4bf88
> SV = PVMG(0xc0fa10) at 0xb4bf88
> REFCNT = 1
> FLAGS = (GMG,SMG)
> IV = 0
> NV = 0
> PV = 0
> MAGIC = 0xc22990
> MG_VIRTUAL = &PL_vtbl_arylen
> MG_TYPE = PERL_MAGIC_arylen(#)
> MG_OBJ = 0xb68298
> ARRAY = 0xba6700
> FILL = 3
> MAX = 3
> ARYLEN = 0xb4bf88
> FLAGS = (REAL)
> Elt No. 0
> SV = IV(0xb84550) at 0xb84558
> REFCNT = 1
> FLAGS = (IOK,pIOK)
> IV = 1
> Elt No. 1
> Elt No. 2
> Elt No. 3
> SV = IV(0xb4bd40) at 0xb4bd48
> REFCNT = 1
> FLAGS = (IOK,pIOK)
> IV = 1
> Start at ./ser_test.pl line 18.
> Ошибка сегментирования
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Sereal/Sereal/issues/128#issuecomment-205367525>
>



-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by nloginoff** [comment]
Perl 5.10 is old version, but many servers still usign this version. We don't have any trouble with array data in other modules (JSON, Storable, Dumper etc), this bug occurs only with this module Sereal::Encoder. I think if we a have a bug, other users may also encounter error. I hope your a fix this issue (we can help you, if is need). We have a old HighLoad project and can't upgrade our perl, but we want change Storable to Sereal.

See attach. This is 2 dump, 1. without $#. 2 with $# - in this dump we a see new block in dump Magic - maube trouble whis it?

[Sereal.txt](https://github.com/Sereal/Sereal/files/204479/Sereal.txt)

**Comment by demerphq** [comment]
This is fixed by b878154.

Since you guys offered to help, a patch adding a test for this behaviour would be appreciated.

Thanks,
Yves

**Comment by nloginoff** [comment]
Thanks a LOT! Fix is working... We a tested this on our test enviroment, before use in production. If we have any troubles i told you.

**Comment by demerphq** [comment]
Any chance you guys will provide a patch to test for this?

**Comment by nloginoff** [comment]
Hi. We write a test, see in branch https://github.com/nloginoff/Sereal/tree/nloginoff-test_for_magic_array_segfault 
Sorry, I can't make pull request into your repository (403 forbidden), I make a Fork and Pull Request.

**Comment by nloginoff** [comment]
I do not see a commit with my text in your repository. I did something wrong?

**Comment by dgryski** [comment]
Diff here https://github.com/Sereal/Sereal/compare/master...nloginoff:nloginoff-test_for_magic_array_segfault

@demerphq for review / merge?

**Comment by demerphq** [comment]
its on my todo list. does anyone know why he couldnt send a normal PR?

is it cause its on a branch?

Yves


On 11 April 2016 at 16:30, Damian Gryski <notifications@github.com> wrote:

> Diff here master...nloginoff:nloginoff-test_for_magic_array_segfault
> <https://github.com/Sereal/Sereal/compare/master...nloginoff:nloginoff-test_for_magic_array_segfault>
>
> @demerphq <https://github.com/demerphq> for review / merge?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Sereal/Sereal/issues/128#issuecomment-208375404>
>



-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by dgryski** [comment]
@nloginoff Can you click your "make pull request" button?

**Comment by nloginoff** [comment]
Send a pull request... But before a don't see this button

**Comment by dgryski** [comment]
Closed with https://github.com/Sereal/Sereal/commit/a2095f9ce2a7898f0550253b027e503fc8db71a9
