### ISSUE TITLE
go: Doesn't handle maps of non-interface types

### ISSUE THREAD

**Issue by bep** [Sereal/Sereal#135]
The following fails:

```go
package main

import (
	"fmt"
	"reflect"

	"github.com/Sereal/Sereal/Go/sereal"
)

type A struct {
	M map[string][]int
}

func main() {

	u := A{M: make(map[string][]int)}

	u.M["k99"] = []int{1, 2, 3}

	b, err := sereal.Marshal(&u)

	if err != nil {
		panic(err)
	}

	decoded := A{}

	err = sereal.Unmarshal(b, &decoded)

	if err != nil {
		panic(err)
	}

	if !reflect.DeepEqual(decoded, u) {
		fmt.Printf(">>> DIFF\n%#v\n%#v\n", u, decoded)
	}
}
```

```
panic: reflect.Value.SetMapIndex: value of type []interface {} is not assignable to type []int
```

**Comment by bep** [comment]
I was hoping that this workaround would work, but this also panics:

```go
package main

import (
	"fmt"
	"reflect"

	"github.com/Sereal/Sereal/Go/sereal"
)

type ints struct {
	v []int
}

type A struct {
	M map[string]ints
}

func main() {

	u := A{M: make(map[string]ints)}

	u.M["k99"] = ints{[]int{1, 2, 3}}

	b, err := sereal.Marshal(&u)

	if err != nil {
		panic(err)
	}

	decoded := A{}

	err = sereal.Unmarshal(b, &decoded)

	if err != nil {
		panic(err)
	}

	if !reflect.DeepEqual(decoded, u) {
		fmt.Printf(">>> DIFF\n%#v\n%#v\n", u, decoded)
	}
}
```

```
panic: reflect.Value.SetMapIndex: value of type map[string]interface {} is not assignable to type main.ints
```

Hmm...

**Comment by dgryski** [comment]
I'll take a look at all of these bugs on Tuesday when I'm back on the office.

**Comment by bep** [comment]
Thanks. Looking at the tests, I notice that all the collection cases (slices, maps) use `interface{}`, which works ... but.

**Comment by dgryski** [comment]
Yes. Some of the features of Sereal make its Perl and dynamic typing heritage evident. It doesn't always play nice with static types, and so Go has to compromise somewhere.

**Comment by bep** [comment]
You know best, but in my head even Perl and PHP types have a static representation on disk.

I have two basic expectations from Sereal Go:

1. What encodes without error should also decode fine.
2. I can do `someinterfacevalue.(int)` it should also be possible for Sereal do so.

**Comment by dgryski** [comment]
Hmm.. This looks like a real bug, since I would have expected this to work.  It looks even when I know the type of the map, I'm creating an `interface{}` instead of a value of the appropriate type to unmarshal into.

I'll fix this.
