### ISSUE TITLE
Hard coded directory separator prevents using `$ENV{SEREAL_TEST_SAVE_OUTPUT}`

### ISSUE THREAD

**Issue by nanis** [Sereal/Sereal#141]
Trying to build `Sereal::Encoder` 3.014 using `perl` 5.24.1-RC2 built with MSVC2013 on Windows 10 Pro 64-bit results in an avalanche of test failures. ([Test report submitted to CPANTesters][report]). While trying to investigate the problem, I set `SEREAL_TEST_SAVE_OUTPUT = 1` in the environment. This prevented tests from running at all because the [`mkpath $dir unless -d $dir;` on line 1199][1] croaks:

<pre>t\700_roundtrip\v1\snappy_canon.t ........ mkdir t\700_roundtrip\v1\snappy_canon.t: File exists; Cannot create a file when that file already exists at t\lib/Sereal/TestSet.pm line 1199.
t\700_roundtrip\v1\snappy_canon.t ........ Dubious, test returned 17 (wstat 4352, 0x1100)
No subtests run</pre>

etc etc.

The reason it croaks is simple. [On the preceding lines][2], you have:

    my $dir= $0;
    $dir=~s!/[^/]+\z!/data/$clean[0]!;

which does not work as intended when `$0` contains Windows style directory separators, i.e. `\`.

It is possible to achieve the desired result using [File::Basename::dirname][3] instead of resorting to regex substitutions. I would recommend doing that. See also "[int main in C and hard coded directory separators in Perl][4]" where I diagnose a similar problem in a different module.

That is, I recommend using `my $dir= File::Spec->catfile(dirname($0), 'data', $clean[0]);` instead of the regex substitution.

[1]: https://metacpan.org/source/YVES/Sereal-Encoder-3.014/t/lib/Sereal/TestSet.pm#L1199
[2]: https://metacpan.org/source/YVES/Sereal-Encoder-3.014/t/lib/Sereal/TestSet.pm#L1197
[3]: https://metacpan.org/pod/File::Basename
[4]: https://www.nu42.com/2014/12/int-main-in-c-and-hard-coded-directory.html
[4]: https://www.nu42.com/2014/12/int-main-in-c-and-hard-coded-directory.html
[report]: http://www.cpantesters.org/cpan/report/21904b5c-6bf7-1014-9852-b545d4813544

**Comment by demerphq** [comment]
I did it a little differently. But it should be fixed in 3.014_002
