### ISSUE TITLE
checking for Sereal: Encoder.so: undefined symbol: newXSproto_portable

### ISSUE THREAD

**Issue by tito80** [Sereal/Sereal#144]
Hi,

I tried to install Sereal::Encoder as a dependency of Sereal package (which again follows from a chain of dependencies). However, now my total thing got screwed up because of this issue in the posting header. Please help.

Thanks,
Tito

**Comment by demerphq** [comment]
Without some kind of build output to review its hard to say much. Sorry. If you can post steps to reproduce we can try to help.

**Comment by dgryski** [comment]
Timed out waiting for info.
