### ISSUE TITLE
missing licenses for spec, python, and ruby implementations at least

### ISSUE THREAD

**Issue by glycerine** [Sereal/Sereal#147]
Irrespective of #63, which is far too long:

a. The top level spec lacks a license. The link at the bottom of the top-level readme dangles. 

Without a license to use the spec, the entire format must be considered off-limits to anybody outside of booking.com. You simply must license the spec (and preferably this entire github repo) if you want to open source Sereal.

b. It's lovely that the Go sub-directory has a 2-clause BSD license. But the python, ruby, and possibly others, lack this authorization. This would also be taken care of by a top level BSD license file. 

Thanks for taking care of this quickly.

**Comment by dgryski** [comment]
I will poke people on Monday about this.

**Comment by demerphq** [comment]
The spec and the perl code are released under the same terms as perl
itself.  Is this not specified somewhere?

**Comment by demerphq** [comment]
Yeah the bottom of the spec says it it is released under the same terms as
perl itself,  which basically means either you must comply with the GPL or
the PAL. Can you clarify why you feel that is insufficient?

Yves

On 11 Sep 2016 15:23, "demerphq" <demerphq@gmail.com> wrote:

The spec and the perl code are released under the same terms as perl
itself.  Is this not specified somewhere?

**Comment by glycerine** [comment]
Neither of those licenses is permissible for commercial software.  That should be abundantly clear by now. It's a data exchange format, for gosh sakes. Why wouldn't you want the widest possible adoption?

Put an MIT or BSD or Apache 2 license on it; If you want me to try it. If you want anyone to adopt it.

**Comment by demerphq** [comment]
On 11 Sep 2016 16:55, "Jason E. Aten, Ph.D." <notifications@github.com>
wrote:
>
> Neither of those licenses is permissible for commercial software. That
should be abundantly clear by now.

Well I am not a lawyer but my understanding is that the the PAL is very
forgiving for commercial reuse. Especially the PAL 2.0. Do you have
references to back up your position on this?

>It's a data exchange format, for gosh sakes. Why wouldn't you want the
widest possible adoption?

This was originally a Perl project and we follow the conventions of the
perl community which is to license under the same terms  as perl itself.
In particular any commercial reuse is allowed provided that either the
modified version is not called Sereal or that modifications to the software
are made available to the main project for integration.

We feel these are reasonable terms to release our work to the world.

Of course we support reuse of our code and spec but we also do not feel
like there are any unreasonable limitations on doing so.  Requiring
substantial modifications to not call themselves Sereal seems quite
reasonable for interoperability reasons.

> Put an MIT or BSD or Apache 2 license on it; If you want me to try it. If
you want anyone to adopt it.

Lots of people in the perl community use  it.

As far as I know the Perl Artistic License 2.0 is not copyleft, it is
permissive just like the Apache or MIT licenses. It is also approved for
integration with GPL and commercial licensing models. It is approved by the
FSF and by the OSI.

Can you please explain what use case is restricted by the terms we
currently license under and we will consider your needs and whether we
should switch our license. But really we need more than your off the cuff
opinion that the software is not suitable for commercial use.  After all
the PAL specifically enables such use under very similar terms to the MIT
license.

Perhaps all we need to do is specify that we license under the 2.0 version
of the PAL.

Yves

**Comment by glycerine** [comment]
Closing this issue out. This software is irrefutably not suited for commercial use.

**Comment by dgryski** [comment]
@glycerine I think what we're trying to get at is:
   1) What are you trying to do with Sereal?
    and
   2) Which clause in the Perl Artistic License 2.0 is preventing you from doing that?
