### ISSUE TITLE
upgrade Go to v4

### ISSUE THREAD

**Issue by dgryski** [Sereal/Sereal#157]
Use cgo bindings for zstd

**Comment by dgryski** [comment]
bindings: https://github.com/DataDog/zstd

**Comment by dgryski** [comment]
This work is completed.  I'm going to push it to a branch for the moment.  The issue is that the `zstd` package master branch is still on 0.5, which means Go isn't able to unpack documents compressed with the perl version, which is at 1.1.3.

There is a `1.x` branch, but "go get" will not work without people manually switching the zstd repo.

Upgrading the `zstd` package to the 1.x master branch was being discussed in https://github.com/DataDog/zstd/issues/4 .  I will try to get this sorted out.

**Comment by ikruglov** [comment]
thanks! I believe that perl version at 1.1.2 though :-)

**Comment by dgryski** [comment]
Fixed :P

**Comment by dgryski** [comment]
https://github.com/Sereal/Sereal/tree/dgryski/go-zstd

**Comment by dgryski** [comment]
"go get" for DataDog's zstd branch brings down 1.1.x; merging.

**Comment by dgryski** [comment]
https://github.com/Sereal/Sereal/commit/3462232ceddf5490686040bcf86c2341f1159018
