### ISSUE TITLE
Sereal::Encoder 4.001_001 produce undecodable result

### ISSUE THREAD

**Issue by ikruglov** [Sereal/Sereal#164]
$ perl -I blib/lib/ -I blib/arch/ -MSereal=encode_sereal,decode_sereal -wle 'decode_sereal(encode_sereal({ a => '1' x 1024}, { snappy_incr => 1, warn_unknown => -1  }))'
Sereal: Error: Invalid zstd packet with unknown uncompressed size at offset 9 of input at ./srl_reader_decompress.h line 187 at -e line 1.

**Comment by dgryski** [comment]
This issue was purely internals of the Perl implementation and shouldn't have affected Go or Java, correct?

**Comment by ikruglov** [comment]
Yes, it is pure implementation problem.
