### ISSUE TITLE
make[1]: don't know how to make ARFLAGS.

### ISSUE THREAD

**Issue by eserte** [Sereal/Sereal#165]
Sereal-Decoder-4.001_002 fails to build on my freebsd smokers (9.2+10.3):
```
Output from '/usr/bin/make':

cp lib/Sereal/Performance.pm blib/lib/Sereal/Performance.pm
cp lib/Sereal/Decoder.pm blib/lib/Sereal/Decoder.pm
cp lib/Sereal/Decoder/Constants.pm blib/lib/Sereal/Decoder/Constants.pm
make[1]: don't know how to make ARFLAGS. Stop

make[1]: stopped in /home/cpansand/.cpan/build/2017042212/Sereal-Decoder-4.001_002-0/zstd
*** Error code 2
```

**Comment by eserte** [comment]
It seems that GNU make specific syntax is used in `zstd/Makefile`. If using `gmake` instead of `make`, then the build works.

**Comment by eserte** [comment]
Same problem exists for Sereal-Encoder-4.001_002

**Comment by ikruglov** [comment]
Thank you for reporting. I'll have a look tonight.

**Comment by ikruglov** [comment]
yeah, it's a problem. How do you suggest solving it? Rewriting Makefile to comply with classical make's syntax or by using gmake? I'm not familiar with this topic well

**Comment by eserte** [comment]
Using gmake _automatically_ is difficult. An Alien-based module may use Alien::gmake, but I don't know of a way to do this cleanly for a non-Alien module.

So probably it's best to stick to simple Makefile syntax.

**Comment by ikruglov** [comment]
make sense to me. Likely the file is small. Shouldn't be much of a problem to rewrite it.

**Comment by ikruglov** [comment]
please try patch in kruglov/bugfix_165

**Comment by eserte** [comment]
Confirmed, works now with BSD make.

**Comment by ikruglov** [comment]
ok, I'll merge then
