### ISSUE TITLE
Perl Sereal::Encoder fails with newer perl development (5.27.3+)

### ISSUE THREAD

**Issue by simcop2387** [Sereal/Sereal#173]
Looks like something changed in newer perls that causes it to go nuts during tests.

http://matrix.cpantesters.org/?dist=Sereal-Encoder%203.015;os=linux;perl=5.27.3;reports=1#sl=2,1

**Comment by simcop2387** [comment]
Here's an RT ticket for the perl side of things.  https://rt.perl.org/Public/Bug/Display.html?id=131852

**Comment by demerphq** [comment]
This should be fixed now in 4.002. Thanks for the report, and sorry for the delay.
