### ISSUE TITLE
Missing a Readme how to use the JavaScript implementation

### ISSUE THREAD

**Issue by steffenw** [Sereal/Sereal#174]
There is all said in headline.

**Comment by ikruglov** [comment]
@danelkhen can you please provide short readme?

**Comment by steffenw** [comment]
Yes please.

**Comment by danelkhen** [comment]
Sure, added readme:
https://github.com/Sereal/Sereal/blob/master/JavaScript/README.md

And added an example web page (needs to run with a web server)
https://github.com/Sereal/Sereal/blob/master/JavaScript/example/index.html
