### ISSUE TITLE
Devel::Checklib improperly included

### ISSUE THREAD

**Issue by danaj** [Sereal/Sereal#177]
From the Devel::Checklib docs:

> If you want to use this from Makefile.PL or Build.PL, do
> not simply copy the module into your distribution as this may cause
> problems when PAUSE and search.cpan.org index the distro.  Instead, use
> the use-devel-checklib script.

Indeed, metacpan now indexes your module as Devel::Checklib.

**Comment by demerphq** [comment]
I don't see a Checklib.pm in our tree, so I am assuming this is from an old version. Please check the latest release 4.002 and if it persists reopen this ticket with more details. Thanks - Yves

**Comment by danaj** [comment]
https://metacpan.org/release/Sereal-Path (4.003) has it, and its meta info indicates this as the repo and issues tracker.  Perhaps that is in error.  Apologies for not putting such basic info in the initial comment.  I will file a Perl RT for that.

**Comment by ikruglov** [comment]
I fail to see how Sereal::Path's setup is different from Sereal which makes it export Devel::CheckLib.

**Comment by demerphq** [comment]
Oh, I see. I should have done a case insensitive search. I found where we use it now. So we use it wrong? Hrm....

**Comment by demerphq** [comment]
Ok, I get it, we need to include a munged version or cpan will list the module. I will push a fix. Since the code is common all packages will see a benefit.

**Comment by demerphq** [comment]
This should be fixed in 4.003 of the Encoder and Decoder - thanks for the report. 

I will leave the ticket open until the other affected packages are rolled out too.

**Comment by danaj** [comment]
It looks correct now.

**Comment by dgryski** [comment]
Can this be closed?

**Comment by danaj** [comment]
As mentioned, this is fixed.  Metacpan correctly indexes.  Closing.
