### ISSUE TITLE
Need a Splitter/Merger/Path release

### ISSUE THREAD

**Issue by demerphq** [Sereal/Sereal#178]
We should do a Splitter/Merger/Path release.

I did some minor code fixes and tweaks for post 4.0 compatibility.

I dont have permissions to do a release or I would do it myself....

Yves

**Comment by ikruglov** [comment]
I will release Path. Merger and Splitter are in unmaintained mode. Perhaps should remove them. I'm not aware of any use cases. @dams, what do you think?

**Comment by dams** [comment]
Splitter's features are more or less provided by Path, so I guess Splitter can go.

**Comment by ikruglov** [comment]
released Sereal::Path with 82c41334242dae6bf740716d34e72ea0179d641a

**Comment by demerphq** [comment]
Dams, Ivan, do you have anything further on this ticket? Can it be closed?
