### ISSUE TITLE
no 'cc' on Windows

### ISSUE THREAD

**Issue by chorny** [Sereal/Sereal#179]
http://www.cpantesters.org/cpan/report/c28afb78-6bf4-1014-ac81-82857a02dcd6
Strawberry perl, different versions.
Makefile for libzstd.o uses default value for $(CC) which is 'cc' and cc is not available.

Possible solution is to add
```
CC       = }.$Config{cc}.q{
```
For me it fixes compilation problems.

**Comment by ikruglov** [comment]
should be fixed. need a release though. @chorny, thanks for reporting!
