### ISSUE TITLE
Uninitialized scalar variable in Perl/shared/zstd/decompress/zstd_decompress.c

### ISSUE THREAD

**Issue by mpw96** [Sereal/Sereal#187]
Hi,
in static seq_t ZSTD_decodeSequence(seqState_t* seqState) there's at least one path of execution that allows leaving the function with field seq.match uninitialized.

This was found by a coverity scan.

Regards
MP

**Comment by demerphq** [comment]
I think we need to update the zstd code to the latest build. We don't maintain it directly.

**Comment by demerphq** [comment]
I am consolidating this under issue #196.
