### ISSUE TITLE
out-of-bounds read in Perl/shared/zstd/compress/zstd_opt.h

### ISSUE THREAD

**Issue by mpw96** [Sereal/Sereal#188]
Hi,
in void ZSTD_compressBlock_opt_generic(ZSTD_CCtx* ctx, const void* src, size_t srcSize, const int ultra), there's a out-of-bounds read in line 523.

This was found by coverity, and the execution path has 283 steps... :-(

Regards
MP

**Comment by demerphq** [comment]
I am consolidating this under issue #196.
