### ISSUE TITLE
Sereal::Decoder->decode_from_file only works when buffer is passed

### ISSUE THREAD

**Issue by Grinnz** [Sereal/Sereal#194]
This works:

    Sereal::Decoder->decode_from_file($filename, my $data);

This does not ($data remains undefined):

    my $data = Sereal::Decoder->decode_from_file($filename);

I suspect it is due to decode_from_file calling ->decode with an undefined second argument if one is not passed.

**Comment by demerphq** [comment]
This is fixed in 4.006, thank you for your report, and my apologies for taking so long to fix such a simple bug. My Bad. :-(
