### ISSUE TITLE
Java decoder cannot decode varint larger than Long.MAX_VALUE

### ISSUE THREAD

**Issue by gohandp** [Sereal/Sereal#204]
I encoded a number(11781050652756758130) using perl encoder which is larger than Java Long.MAX_VALUE and while decoding it through Java decoder library it returns -6665693420952793486 due to byte overflow.

I have created a unit test for this, but don't have any permissions on the branch so providing a link to the diff https://pastebin.com/6USXK2KK

**Comment by mbarbon** [comment]
Unless you have objections, I am going to change the decoder to return a `BigInteger` in this case.

**Comment by gohandp** [comment]
Yes, please go ahead.
