### ISSUE TITLE
Java release 

### ISSUE THREAD

**Issue by Fokko** [Sereal/Sereal#205]
It is quite a while ago since the latest Java release: https://mvnrepository.com/artifact/com.serial/serial/0.1

Would be possible to do a release soon? We're using 0.2-SNAPSHOT right now, but this isn't really convenient with our CI process since we have to compile and publish it to the local repository.

Cheers, Fokko

**Comment by demerphq** [comment]
Sorry for not replying earlier, did this get resolved  or did you close it
out of frustration  with not getting a reply?

Im not the java dev on this project but i can poke the guys who are and hrt
them to roll a release.

Yves
