### ISSUE TITLE
Little help needed

### ISSUE THREAD

**Issue by Chayyoo** [Sereal/Sereal#209]
I'm trying to replace Storable by Sereal in a perl script, but it fails when trying to write and read to disk.
This works:
```
use Sereal qw(read_sereal write_sereal encode_sereal decode_sereal);
my %hash = ("A" => "a", "B" => "b");
my $model=encode_sereal(\%hash);
my $model_ref=decode_sereal($model);
while (my ($k, $v) = each %$model_ref) {
    print "$k $v\n";
}

```
But this doesn't:

```
use Sereal qw(read_sereal write_sereal encode_sereal decode_sereal);
my %hash = ("A" => "a", "B" => "b");
write_sereal('tst_serial.sdb', \%hash, 0);
read_sereal('tst_serial.sdb', my $model_ref) or die "$!";
while (my ($k, $v) = each %$model_ref) {
    print "$k $v\n";
}

```
It prints nothing. Why is that?

**Comment by demerphq** [comment]
I'm out right now, will check later in detail, but which version exactly
are you using, there was a stupid in a release related to this convenience
wrapper code and I don't remember if I released a non Dev version yet

**Comment by Chayyoo** [comment]
Found it. The correct syntax is:
`read_sereal($file, $OPT; $ROOT), so I need to write:
read_sereal('tst_serial.sdb, {}, my $model_ref) or die "$!";

`

**Comment by dgryski** [comment]
Closing.
