### ISSUE TITLE
Infinite recursion on bad sereal data using COPY tag (in Python decoder)

### ISSUE THREAD

**Issue by denilsonsa** [Sereal/Sereal#211]
In the code below:

    =\xf3rl   Magic string
    \x04      Version type
    \x00      Header suffix size (zero)
    +\x03     Arrray (of size 3)
    \t        First element, integer 9.
    /\x03     COPY, with the offset being either 3 (copying the integer 9) or 4 (copying the COPY tag).
    \n        Third element, integer 10.

```python
import sereal.decoder
good = b'=\xf3rl\x04\x00+\x03\t/\x03\n'
bad  = b'=\xf3rl\x04\x00+\x03\t/\x04\n'
for data in [good, bad]:
    print(sereal.decoder.SrlDecoder().decode(data))
```

Results:

    [9, 9, 10]
    RecursionError: maximum recursion depth exceeded

The spec says it is forbidden for a COPY tag to refer to another COPY (with one exception that I could not understand).

Expectation:

The library should raise a `SrlError` exception for invalid Sereal data, instead of crashing. After all, such exception can be easily caught by the caller code.

Sidenote: I'm confused about the COPY offset, as it seems to start counting from 1.

**Comment by dgryski** [comment]
I believe only the Go and Perl decoders have been fuzzed.  The Python and Java ones are probably not as safe against invalid inputs.

**Comment by cerasmus** [comment]
b52336640f0b7c2e433e1b69dd8711117d37af9c on cerasmus/recursive_copy_tag

Please see if this looks good to you and I'll merge to master.

**Comment by demerphq** [comment]
On Fri, 8 Nov 2019, 14:00 Denilson Sá Maia, <notifications@github.com>
wrote:

> In the code below:
>
> =\xf3rl   Magic string
> \x04      Version type
> \x00      Header suffix size (zero)
> +\x03     Arrray (of size 3)
> \t        First element, integer 9.
> /\x03     COPY, with the offset being either 3 (copying the integer 9) or 4 (copying the COPY tag).
> \n        Third element, integer 10.
>
> import sereal.decoder
> good = b'=\xf3rl\x04\x00+\x03\t/\x03\n'
> bad  = b'=\xf3rl\x04\x00+\x03\t/\x04\n'for data in [good, bad]:
>     print(sereal.decoder.SrlDecoder().decode(data))
>
> Results:
>
> [9, 9, 10]
> RecursionError: maximum recursion depth exceeded
>
> The spec says it is forbidden for a COPY tag to refer to another COPY
> (with one exception that I could not understand).
>
This is an exception which allows to be used to copy a complex tag that
itself uses COPY tags for simple purposes like strings. In practice COPY is
used primarily for strings like hash keys and class names. If you have a
thousand objects with the same class name we output the class name only
once.

Sidenote: I'm confused about the COPY offset, as it seems to start counting
> from 1.
>
It was convenient to assume offsets are nonzero. Originally they were
against document start, which meant they were always nonzero as copy tags
only refer to content in the body. But this made it impossible to change
the size of the header after constructing the body. So offsets were changed
to be against body start and to preserve the "can not be zero" we treat
them as 1 indexed values. So an offset to the first byte in the body (byte
0) is offset 1. Strictly speaking it is still an offset, from the last byte
of the header. 😀

Yves
