### ISSUE TITLE
Test::MemoryGrowth only supported on Linux

### ISSUE THREAD

**Issue by grr** [Sereal/Sereal#232]
commit 9aa22a7ebc6e17dc197125bafa52296a381447d6 added Test::MemoryGrowth as a prereq, but that module only works under linux and will die upon install on a non-linux system.  either make the use of it conditional, or choose a more portable alternative.

**Comment by demerphq** [comment]
On Thu, 11 Jun 2020 at 12:56, grr <notifications@github.com> wrote:

> commit 9aa22a7
> <https://github.com/Sereal/Sereal/commit/9aa22a7ebc6e17dc197125bafa52296a381447d6>
> added Test::MemoryGrowth as a prereq, but that module only works under
> linux and will die upon install on a non-linux system. either make the use
> of it conditional, or choose a more portable alternative.
>
Ah. I see. Ok, umm, is there a more portable alternative you can recommend?

Ill get a new version out today hopefully. Sorry about that.

Yves


-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by grr** [comment]
> Ah. I see. Ok, umm, is there a more portable alternative you can recommend?

i generally use Test::LeakTrace, but it looks like Test::MemoryGrowth checks for leaks from outside of perl, so if you want the same behavior you can directly use Proc::ProcessTable and check the `rss` of the process before and after the code block is called.

**Comment by demerphq** [comment]
I just pushed 4.014 with a fix for this, so ill close for now. Thanks for the report!
