### ISSUE TITLE
Sereal::Decoder build failure under parallel make: zstd/libzstd.o not found

### ISSUE THREAD

**Issue by mohawk2** [Sereal/Sereal#260]
I've just tried to install Sereal::Decoder with parallel make. It failed, saying `zstd/libzstd.o` not found. However it worked when re-running with `MAKEFLAGS` unset. I assume a dependency is not set right.

**Comment by zmughal** [comment]
This only occurs when building with the bundled `zstd`.

To replicate run the following with and without the `libzstd-dev` package:

```shell
$ docker run -it --rm perl:5.34 bash -c '
    apt-get update && apt-get install libzstd-dev;
    export MAKEFLAGS=-j4;
    cpanm -qn --installdeps Sereal::Decoder;
    cpanm --test-only --verbose Sereal::Decoder'
```
