### ISSUE TITLE
(Perl) wrong order used for THAWing nested objects?

### ISSUE THREAD

**Issue by mfontani** [Sereal/Sereal#283]
The docs say:

> As of v4.024 frozen representations may contain other objects, and the order in which they are thawed is defined to be LIFO, thus the arguments to a THAW method will themselves be thawed (if need be) before the call to the containing objects THAW method. Thawing occurs only after all simple objects have been blessed into their appropriate object form.

I would therefore expect that in case I have an "outer" object which uses FREEZE/THAW containing "inner" objects which also use FREEZE/THAW, however nested, those *inner* objects should be THAWed first, and only lastly the "outer" object should be THAWed, and should be given _thawed object insstances_, and not "internal/intermediate representation of their frozen state", as it seemingly happens.

I've tested the same script using:

- CBOR::XS
- JSON::XS
- Cpanel::JSON::XS
- Sereal

And all but the latter (i.e. Sereal) get the order right: "inner, then outer".

See https://gist.github.com/mfontani/48c8ff4c98c2d32d43be65b5a2c04c0e for an example test script which serializes/deserializes a deeply nested object structure which includes objects which need FREEZE/THAW applied.

I did a `git bisect`, with master being "bad" and I found that the order was "right" in tag `Sereal-4.023`.

Unfortunately the bisect didn't work to pinpoint a specific commit, as some of them didn't compile and hence I couldn't test them.

- tag `Sereal-4.024` didn't compile
- 94df2087a2f4b1e0490411d655a476e1400935bc "Rework how we handled frozen objects.", likely culprit? didn't compile either
- 0833c44b7bb6cd1d62d68e484c234b21a845f7e7 "Fixups for Encoder/t/020_sort_keys" works, though, after which bisect tells me:

```bash
$ git bisect good
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
94df2087a2f4b1e0490411d655a476e1400935bc
e2afdf3778222d32bfb11bff890868116def0f76
cf78dcdc78a517d4228a01cfd30386f181571b02
We cannot bisect more!
```

... so I'm not sure how to further troubleshoot when/where this started happening.

I think the "changes to FREEZE/THAW mechanism" which came in 4.024 are likely to blame:

> 4.024 Wed Jul 27, 2022
> Total rework of how THAW is invoked to resolve issues with frozen representations containing blessed objects.

That's also where the piece of documentation about "the order in which they are thawed is defined to be LIFO, thus the arguments to a THAW method will themselves be thawed (if needs be) *before* the call to the *containing* object's thaw method" (emphasis mine) ... and "The FREEZE/THAW mechanism is inspired by the equivalent mechanism in CBOR::XS".

That doesn't seem to be the case. It's seemingly doing things "the wrong way around".

Am I doing something wrong, or is Sereal?

----

To be clear, here's some sample output that explains the problem from my PoV: CBOR, JSON::XS and Cpanel::JSON::XS all serialize (via FREEZE) outside-in and de-serialize (via the same THAW) the _inner_ data structures first (inside-out):

```bash
$ carton exec -- perl roundtrip.pl
Encoding with CBOR...
CBOR encoding steps:
  - FooOutside::FREEZE(bless( {'inside' => {'1' => bless( {'attrs' => {},'inside' => {'0' => bless( {'inside' => {'0' => 'fourth/inner'},'attrs' => {}}, 'FooInside' )}}, 'FooOutside' ),'0' => bless( {'attrs' => {},'inside' => {'0' => 'second/not_frozen','1' => 'third/not_frozen'}}, 'FooInside' )},'attrs' => {'attr1' => 'foobar','bar' => bless( {'inside' => {'0' => 'should_be_first'},'attrs' => {}}, 'FooInside' )}}, 'FooOutside' ))
  - FooInside::FREEZE(bless( {'inside' => {'0' => 'should_be_first'},'attrs' => {}}, 'FooInside' ))
  - FooInside::FREEZE(bless( {'attrs' => {},'inside' => {'0' => 'second/not_frozen','1' => 'third/not_frozen'}}, 'FooInside' ))
  - FooOutside::FREEZE(bless( {'attrs' => {},'inside' => {'0' => bless( {'inside' => {'0' => 'fourth/inner'},'attrs' => {}}, 'FooInside' )}}, 'FooOutside' ))
  - FooInside::FREEZE(bless( {'inside' => {'0' => 'fourth/inner'},'attrs' => {}}, 'FooInside' ))
CBOR decoding steps:
  - FooInside::THAW({'inside' => ['should_be_first'],'attrs' => {}})
  - FooInside::THAW({'inside' => ['second/not_frozen','third/not_frozen'],'attrs' => {}})
  - FooInside::THAW({'attrs' => {},'inside' => ['fourth/inner']})
  - FooOutside::THAW({'attrs' => {},'inside' => [bless( {'attrs' => {},'inside' => {'0' => 'fourth/inner'}}, 'FooInside' )]})
  - FooOutside::THAW({'inside' => [bless( {'attrs' => {},'inside' => {'1' => 'third/not_frozen','0' => 'second/not_frozen'}}, 'FooInside' ),bless( {'attrs' => {},'inside' => {'0' => bless( {'attrs' => {},'inside' => {'0' => 'fourth/inner'}}, 'FooInside' )}}, 'FooOutside' )],'attrs' => {'bar' => bless( {'attrs' => {},'inside' => {'0' => 'should_be_first'}}, 'FooInside' ),'attr1' => 'foobar'}})
Encoding with JSON::XS...
JSON::XS encoding steps:
  - FooOutside::FREEZE(bless( {'inside' => {'1' => bless( {'attrs' => {},'inside' => {'0' => bless( {'attrs' => {},'inside' => {'0' => 'fourth/inner'}}, 'FooInside' )}}, 'FooOutside' ),'0' => bless( {'attrs' => {},'inside' => {'0' => 'second/not_frozen','1' => 'third/not_frozen'}}, 'FooInside' )},'attrs' => {'bar' => bless( {'inside' => {'0' => 'should_be_first'},'attrs' => {}}, 'FooInside' ),'attr1' => 'foobar'}}, 'FooOutside' ))
  - FooInside::FREEZE(bless( {'attrs' => {},'inside' => {'0' => 'second/not_frozen','1' => 'third/not_frozen'}}, 'FooInside' ))
  - FooOutside::FREEZE(bless( {'attrs' => {},'inside' => {'0' => bless( {'attrs' => {},'inside' => {'0' => 'fourth/inner'}}, 'FooInside' )}}, 'FooOutside' ))
  - FooInside::FREEZE(bless( {'attrs' => {},'inside' => {'0' => 'fourth/inner'}}, 'FooInside' ))
  - FooInside::FREEZE(bless( {'inside' => {'0' => 'should_be_first'},'attrs' => {}}, 'FooInside' ))
JSON::XS decoding steps:
  - FooInside::THAW({'attrs' => {},'inside' => ['second/not_frozen','third/not_frozen']})
  - FooInside::THAW({'inside' => ['fourth/inner'],'attrs' => {}})
  - FooOutside::THAW({'attrs' => {},'inside' => [bless( {'inside' => {'0' => 'fourth/inner'},'attrs' => {}}, 'FooInside' )]})
  - FooInside::THAW({'attrs' => {},'inside' => ['should_be_first']})
  - FooOutside::THAW({'attrs' => {'bar' => bless( {'inside' => {'0' => 'should_be_first'},'attrs' => {}}, 'FooInside' ),'attr1' => 'foobar'},'inside' => [bless( {'inside' => {'0' => 'second/not_frozen','1' => 'third/not_frozen'},'attrs' => {}}, 'FooInside' ),bless( {'inside' => {'0' => bless( {'inside' => {'0' => 'fourth/inner'},'attrs' => {}}, 'FooInside' )},'attrs' => {}}, 'FooOutside' )]})
Encoding with Cpanel::JSON::XS...
Cpanel::JSON::XS encoding steps:
  - FooOutside::FREEZE(bless( {'inside' => {'1' => bless( {'attrs' => {},'inside' => {'0' => bless( {'inside' => {'0' => 'fourth/inner'},'attrs' => {}}, 'FooInside' )}}, 'FooOutside' ),'0' => bless( {'inside' => {'1' => 'third/not_frozen','0' => 'second/not_frozen'},'attrs' => {}}, 'FooInside' )},'attrs' => {'bar' => bless( {'inside' => {'0' => 'should_be_first'},'attrs' => {}}, 'FooInside' ),'attr1' => 'foobar'}}, 'FooOutside' ))
  - FooInside::FREEZE(bless( {'inside' => {'0' => 'should_be_first'},'attrs' => {}}, 'FooInside' ))
  - FooInside::FREEZE(bless( {'inside' => {'1' => 'third/not_frozen','0' => 'second/not_frozen'},'attrs' => {}}, 'FooInside' ))
  - FooOutside::FREEZE(bless( {'attrs' => {},'inside' => {'0' => bless( {'inside' => {'0' => 'fourth/inner'},'attrs' => {}}, 'FooInside' )}}, 'FooOutside' ))
  - FooInside::FREEZE(bless( {'inside' => {'0' => 'fourth/inner'},'attrs' => {}}, 'FooInside' ))
Cpanel::JSON::XS decoding steps:
  - FooInside::THAW({'attrs' => {},'inside' => ['should_be_first']})
  - FooInside::THAW({'attrs' => {},'inside' => ['second/not_frozen','third/not_frozen']})
  - FooInside::THAW({'inside' => ['fourth/inner'],'attrs' => {}})
  - FooOutside::THAW({'attrs' => {},'inside' => [bless( {'attrs' => {},'inside' => {'0' => 'fourth/inner'}}, 'FooInside' )]})
  - FooOutside::THAW({'inside' => [bless( {'attrs' => {},'inside' => {'0' => 'second/not_frozen','1' => 'third/not_frozen'}}, 'FooInside' ),bless( {'attrs' => {},'inside' => {'0' => bless( {'attrs' => {},'inside' => {'0' => 'fourth/inner'}}, 'FooInside' )}}, 'FooOutside' )],'attrs' => {'bar' => bless( {'inside' => {'0' => 'should_be_first'},'attrs' => {}}, 'FooInside' ),'attr1' => 'foobar'}})
Encoding with Sereal...
Sereal encoding steps:
  - FooOutside::FREEZE(bless( {'attrs' => {'bar' => bless( {'inside' => {'0' => 'should_be_first'},'attrs' => {}}, 'FooInside' ),'attr1' => 'foobar'},'inside' => {'1' => bless( {'attrs' => {},'inside' => {'0' => bless( {'attrs' => {},'inside' => {'0' => 'fourth/inner'}}, 'FooInside' )}}, 'FooOutside' ),'0' => bless( {'attrs' => {},'inside' => {'0' => 'second/not_frozen','1' => 'third/not_frozen'}}, 'FooInside' )}}, 'FooOutside' ))
  - FooInside::FREEZE(bless( {'inside' => {'0' => 'should_be_first'},'attrs' => {}}, 'FooInside' ))
  - FooInside::FREEZE(bless( {'attrs' => {},'inside' => {'0' => 'second/not_frozen','1' => 'third/not_frozen'}}, 'FooInside' ))
  - FooOutside::FREEZE(bless( {'attrs' => {},'inside' => {'0' => bless( {'attrs' => {},'inside' => {'0' => 'fourth/inner'}}, 'FooInside' )}}, 'FooOutside' ))
  - FooInside::FREEZE(bless( {'attrs' => {},'inside' => {'0' => 'fourth/inner'}}, 'FooInside' ))
```

Sereal does the right thing at serialization time, but the opposite at de-serialization time:

```bash
Sereal decoding steps:
  - FooOutside::THAW({'inside' => [[{'inside' => ['second/not_frozen','third/not_frozen'],'attrs' => {}}],[{'inside' => [[{'inside' => ['fourth/inner'],'attrs' => {}}]],'attrs' => {}}]],'attrs' => {'attr1' => 'foobar','bar' => [{'inside' => ['should_be_first'],'attrs' => {}}]}})
  - FooOutside::THAW({'inside' => [[{'inside' => ['fourth/inner'],'attrs' => {}}]],'attrs' => {}})
  - FooInside::THAW({'inside' => ['fourth/inner'],'attrs' => {}})
  - FooInside::THAW({'inside' => ['second/not_frozen','third/not_frozen'],'attrs' => {}})
  - FooInside::THAW({'inside' => ['should_be_first'],'attrs' => {}})
```

What's worth of note is that the `FooOutside::THAW` _isn't_ given a "thawed object", but rather Sereal's/"the" intermediate frozen representation of it, so it can't really thaw properly.

**Comment by mauke** [comment]
Even more reduced:
```perl
use v5.36.0;
use Sereal qw(encode_sereal decode_sereal);
use Data::Dumper;

{
    package Dummy;

    sub new($class, $value) {
        my $self = bless { value => $value }, $class;
        say "?->new: creating $self with $value";
        $self
    }

    sub FREEZE($self, $type) {
        say "?->FREEZE: freezing $self -> $self->{value}";
        $self->{value}
    }

    sub THAW($class, $type, $value) {
        say "?->THAW: thawing $value";
        $class->new($value)
    }
}

my $obj = Dummy->new(Dummy->new(42));
say "original object $obj: ", Dumper $obj;

my $bytes = encode_sereal $obj, { freeze_callbacks => 1 };
$obj = undef;

my $obj2 = decode_sereal $bytes;
say "thawed object $obj2: ", Dumper $obj2;
```
Output:
```
?->new: creating Dummy=HASH(0x559c350175e8) with 42
?->new: creating Dummy=HASH(0x559c350177c8) with Dummy=HASH(0x559c350175e8)
original object Dummy=HASH(0x559c350177c8): $VAR1 = bless( {
                 'value' => bless( {
                                     'value' => 42
                                   }, 'Dummy' )
               }, 'Dummy' );

?->FREEZE: freezing Dummy=HASH(0x559c350177c8) -> Dummy=HASH(0x559c350175e8)
?->FREEZE: freezing Dummy=HASH(0x559c350175e8) -> 42
?->THAW: thawing ARRAY(0x559c3503db40)
?->new: creating Dummy=HASH(0x559c351d1cc0) with ARRAY(0x559c3503db40)
?->THAW: thawing 42
?->new: creating Dummy=HASH(0x559c3516e530) with 42
thawed object Dummy=HASH(0x559c351d1cc0): $VAR1 = bless( {
                 'value' => [
                              42
                            ]
               }, 'Dummy' );

```
Things to note:

- The `THAW` method is called with an ARRAY ref, which violates the FREEZE/THAW protocol: `THAW` is only supposed to be called as `$class->THAW($serializer, @args)` where `@args` is the list of values returned from `FREEZE`:
  
      ?->THAW: thawing ARRAY(0x559c3503db40)

- The inner object (`Dummy=HASH(0x559c3516e530) with 42`) was deserialized, but not returned anywhere.

**Comment by demerphq** [comment]
I will take a look, thanks.

You (@mfontani) said:

>https://github.com/Sereal/Sereal/commit/94df2087a2f4b1e0490411d655a476e1400935bc "Rework how we handled frozen objects.", likely culprit? didn't compile either

But it compiles for me. could you show me the error you see?

The output you showed is from which version of Sereal?

> What's worth of note is that the FooOutside::THAW isn't given a "thawed object", but rather Sereal's/"the" intermediate frozen representation of it, so it can't really thaw properly.

Well, you could just do the right thing by checking the deserializer name. :-) its not like it /can't/ thaw properly. But i agree that isn't ideal. Having said that I do recall there was something controversial involved that made this less clearly a bug than it seems at first, but right now the details elude me. Ill do some follow up and get back to you.

**Comment by mfontani** [comment]
> > [94df208](https://github.com/Sereal/Sereal/commit/94df2087a2f4b1e0490411d655a476e1400935bc) "Rework how we handled frozen objects.", likely culprit? didn't compile either
> 
> But it compiles for me. could you show me the error you see?

Sure. https://gist.github.com/mfontani/6ea3ed270a58300b6d9cb89965c9c1ac

There's various errors related to:
- use of undeclared identifier "my_perl"
- too many arguments to function call, expected 3, have 4 for srl_fetch_register_frozen_object
- and for srl_track_frozen_object

> The output you showed is from which version of Sereal?

Latest.  The script was launched with a cpanfile:

```bash
$ command cat cpanfile
requires 'Sereal::Encoder' => '== 5.003';
requires 'Sereal::Decoder' => '== 5.003';
requires 'JSON::XS' => '== 4.03';
requires 'Cpanel::JSON::XS' => '== 4.36';
requires 'CBOR::XS' => '== 1.86';
requires 'Data::Dumper' => '== 2.183';
```

> > What's worth of note is that the FooOutside::THAW isn't given a "thawed object", but rather Sereal's/"the" intermediate frozen representation of it, so it can't really thaw properly.
> 
> Well, you could just do the right thing by checking the deserializer name. :-) its not like it /can't/ thaw properly.

I could for a very limited case: where I'm fully in control of the FREEZE/THAW subs called across the whole freezing and thawing chain.

If I'm serializing/deserializing something that _contains_ a foreign object that has their own FREEZE/THAW I'd be none the wiser, and if I want to use that object deeply nested I'd have to override its FREEZE/THAW in my own package, all because... it doesn't work right?

> But i agree that isn't ideal. Having said that I do recall there was something controversial involved that made this less clearly a bug than it seems at first, but right now the details elude me. Ill do some follow up and get back to you.

Thanks for that.

I just noticed that the tests added in 94df2087a2f4b1e0490411d655a476e1400935bc stop short at... testing objects which use FREEZE/THAW _inside of_ objects which use FREEZE/THAW: it only tests one level deep, but the change done affects/affected nested ones.

**Comment by mfontani** [comment]
I've opened a PR for that, with a test that exercises (minimally) that the children are thawed before the fathers. It would be better to expand on it using other tests to ensure the order is the "right" one not only father/child but also when it comes to siblings, as well as testing a much deeper nesting.

**Comment by mfontani** [comment]
Scratch that, it's not quite where it should be:

```bash
Cpanel::JSON::XS decoding steps:
  - FooInside::THAW({'inside' => ['should_be_first'],'attrs' => {}})
  - FooInside::THAW({'inside' => ['second/not_frozen','third/not_frozen'],'attrs' => {}})
  - FooInside::THAW({'attrs' => {},'inside' => ['fourth/inner']})
  - FooOutside::THAW({'attrs' => {},'inside' => [bless( {'inside' => {'0' => 'fourth/inner'},'attrs' => {}}, 'FooInside' )]})
  - FooOutside::THAW({'inside' => [bless( {'inside' => {'1' => 'third/not_frozen','0' => 'second/not_frozen'},'attrs' => {}}, 'FooInside' ),bless( {'attrs' => {},'inside' => {'0' => bless( {'inside' => {'0' => 'fourth/inner'},'attrs' => {}}, 'FooInside' )}}, 'FooOutside' )],'attrs' => {'bar' => bless( {'attrs' => {},'inside' => {'0' => 'should_be_first'}}, 'FooInside' ),'attr1' => 'foobar'}})
Encoding with Sereal...
Sereal encoding steps:
  - FooOutside::FREEZE(bless( {'inside' => {'0' => bless( {'attrs' => {},'inside' => {'0' => 'second/not_frozen','1' => 'third/not_frozen'}}, 'FooInside' ),'1' => bless( {'attrs' => {},'inside' => {'0' => bless( {'attrs' => {},'inside' => {'0' => 'fourth/inner'}}, 'FooInside' )}}, 'FooOutside' )},'attrs' => {'bar' => bless( {'inside' => {'0' => 'should_be_first'},'attrs' => {}}, 'FooInside' ),'attr1' => 'foobar'}}, 'FooOutside' ))
  - FooInside::FREEZE(bless( {'attrs' => {},'inside' => {'0' => 'second/not_frozen','1' => 'third/not_frozen'}}, 'FooInside' ))
  - FooOutside::FREEZE(bless( {'attrs' => {},'inside' => {'0' => bless( {'attrs' => {},'inside' => {'0' => 'fourth/inner'}}, 'FooInside' )}}, 'FooOutside' ))
  - FooInside::FREEZE(bless( {'attrs' => {},'inside' => {'0' => 'fourth/inner'}}, 'FooInside' ))
  - FooInside::FREEZE(bless( {'inside' => {'0' => 'should_be_first'},'attrs' => {}}, 'FooInside' ))
Sereal decoding steps:
  - FooOutside::THAW({'inside' => [[{'attrs' => {},'inside' => ['second/not_frozen','third/not_frozen']}],[{'inside' => [[{'inside' => ['fourth/inner'],'attrs' => {}}]],'attrs' => {}}]],'attrs' => {'bar' => [{'inside' => ['should_be_first'],'attrs' => {}}],'attr1' => 'foobar'}})
  - FooInside::THAW({'inside' => ['should_be_first'],'attrs' => {}})
  - FooOutside::THAW({'inside' => [[{'inside' => ['fourth/inner'],'attrs' => {}}]],'attrs' => {}})
  - FooInside::THAW({'inside' => ['fourth/inner'],'attrs' => {}})
  - FooInside::THAW({'attrs' => {},'inside' => ['second/not_frozen','third/not_frozen']})
```

**Comment by demerphq** [comment]
Yeah, switching from pop to shift is one approach. The bug/thinko in my original patch is that is srl_read_frozen_object() is calling srl_read_single_value() before it calls srl_track_frozen_object() instead of the other way around. But you can't /just/ switch them around, as srl_track_frozen_object() does SvRV() on SV into. Your patch might be the solution that avoids having to fix this, but I have to admit i am not sure what else it might break and if I can fix it so that the srl_read_frozen_object() does the right thing, I think I would prefer that approach.  I need to think about this a bit.

**Comment by demerphq** [comment]
I think that https://github.com/Sereal/Sereal/pull/285 should do it, could you please check? I turned your original test case into a new test, similar to what you did in #284, but closer to your gist from this report:

https://gist.github.com/mfontani/48c8ff4c98c2d32d43be65b5a2c04c0e

If this seems right to you then ill tag it up and release it.

**Comment by mfontani** [comment]
All looks good to me.  I'd recommend adding this as a test, to ensure that the data structures not only don't differ in shape, but also in internal blessedness of internal items (which is_deeply doesn't seem to test for):

```patch
diff --git a/Perl/Decoder/t/091_thaw_order.t b/Perl/Decoder/t/091_thaw_order.t
index 153a8a81..7b996ddd 100644
--- a/Perl/Decoder/t/091_thaw_order.t
+++ b/Perl/Decoder/t/091_thaw_order.t
@@ -128,4 +128,6 @@ is_deeply(\@steps, [

 is_deeply($dec, $struct, "And the final structures match");

+is(dd($struct), dd($dec), "And the dump of both structures matches");
+
 done_testing;
```
