### ISSUE TITLE
Wrong cyclic_weakrefs.t name in Sereal-Encoder-3.004's MANIFEST

### ISSUE THREAD

**Issue by ppisar** [Sereal/Sereal#75]
Sereal-Encoder-3.004's MANIFEST lists t/170-cyclic_weakrefs.t, but the file is named t/170_cyclic_weakrefs.t. There is a underscore/hyphen typo.

**Comment by demerphq** [comment]
On 5 January 2015 at 13:39, ppisar <notifications@github.com> wrote:

> Sereal-Encoder-3.004's MANIFEST lists t/170-cyclic_weakrefs.t, but the
> file is named t/170_cyclic_weakrefs.t. There is a underscore/hyphen typo.
>

Thanks, this is a known issue and will be fixed in 3.005 which should be
released soon.

Yves


-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by demerphq** [comment]
Fixed in 3.005
