### ISSUE TITLE
Cannot add Sereal 3.005 to a Pinto repository 

### ISSUE THREAD

**Issue by maxhq** [Sereal/Sereal#79]
I think this is more a *Sereal* problem than a *Pinto* problem (or at least more easy to solve here):
When trying ```pinto pull Sereal``` it fails with: *Sereal-Encoder-3.005.tar.gz contains no packages and will not be in the index*

As far as I can see, it all boils down to *Module::Metadata*'s way to extract version numbers which is kind of incompatible with *Sereal*'s specification in *Sereal::[De|En]coder::Constants*.
The solution would be to directly specify the package version instead of referencing *Sereal::[De|En]coder*.

I have to mention that I also opened a [ticket for Module::Metadata](https://rt.cpan.org/Ticket/Display.html?id=101773) with a proposal how to solve the problem, but I a) don't have deep knowledge about *Module::Metadata* and b) think it would take quite some effort to fix it there.

**Comment by demerphq** [comment]
On 27 January 2015 at 18:21, Jens Berthold <notifications@github.com> wrote:

> I think this is more a *Sereal* problem than a *Pinto* problem (or at
> least more easy to solve here):
> When trying pinto pull Sereal it fails with: *Sereal-Encoder-3.005.tar.gz
> contains no packages and will not be in the index*
>
> As far as I can see, it all boils down to *Module::Metadata*'s way to
> extract version numbers which is kind of incompatible with *Sereal*'s
> specification in *Sereal::[De|En]coder::Constants*.
> The solution would be to directly specify the package version instead of
> referencing *Sereal::[De|En]coder*.
>
This is done in 3.005_001

perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by maxhq** [comment]
Whoaa.. that was fast, I'm scared ;-)
But now I saw you also fixed some other issues.
Anyway - thank you very much!
