### ISSUE TITLE
undef values in shared arrays

### ISSUE THREAD

**Issue by mnz2000** [Sereal/Sereal#97]
This works:

    use strict;
    use threads;
    use threads::shared;
    use Sereal;
    my $dat=shared_clone([1,2,3,4]);
    my $enc = Sereal::Encoder->new();
    my $encoded=$enc->encode($dat);

This doesn't:

    use strict;
    use threads;
    use threads::shared;
    use Sereal;
    my $dat=shared_clone([1,undef,3,4]);
    my $enc = Sereal::Encoder->new();
    my $encoded=$enc->encode($dat);

It reports the following:

    Found type 10 SCALAR(0x359a3c), but it is not representable by the Sereal encoding format at test.pl line 8.

Tested on ActiveState Perl versions 5.16.3 and 5.18.2. Sereal version is 3.005.

**Comment by demerphq** [comment]
Thanks for the report. Sorry for taking so long to notice. We will see what we can do about this.

**Comment by demerphq** [comment]
This should be fixed in 3.006_004
