### ISSUE TITLE
Issues with the FREEZE/THAW API serialization when perl is < 5.10

### ISSUE THREAD

**Issue by chansen** [Sereal/Sereal#98]
Since I released Time::Moment 0.15 with support with the generic FREEZE/THAW API, I have received failure reports from every release (now 0.25) from CPAN Testers relating to Sereal. The failure reports is using a Perl version less than 5.10. If you analyze the limited output providing from the CPAN Testers, it seems there is an issue with non printable characters.

I plan to disable the serialization tests for Sereal if the perl version is less than 5.10 unless you you have any ideas or want input from my distribution.

Start browsing here:
http://www.cpantesters.org/distro/T/Time-Moment.html?oncpan=1&distmat=1&version=0.15&grade=3
## Regards

chansen

**Comment by demerphq** [comment]
On 12 July 2015 at 15:11, Christian Hansen <notifications@github.com> wrote:

> Since I released Time::Moment 0.15 with support with the generic
> FREEZE/THAW API, I have received failure reports from every release (now
> 0.25) from CPAN Testers relating to Sereal. The failure reports is using a
> Perl version less than 5.10. If you analyze the limited output providing
> from the CPAN Testers, it seems there is an issue with non printable
> characters.
>

Can you change your test script to use something like
Data::Dumper::qquote() to output the string you got please? That way I can
see what is different.


> I plan to disable the serialization tests for Sereal if the perl version
> is less than 5.10 unless you you have any ideas or want input from my
> distribution.
>

I dont have ideas yet, but I would like to see more info about what is
different in these strings. Perhaps something like

is($decoded->[0], $moments[0]->to_string, 'first element has right
time') or diag "Got " . Data::Dumper::qquote($decoded->[0]);


Yves


-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by chansen** [comment]
I'll add a diagnostic call in next release and get back to you when I have received some smoke failures.

--
chansen

**Comment by demerphq** [comment]
On 15 July 2015 at 10:27, Christian Hansen <notifications@github.com> wrote:

> I'll add a diagnostic call in next release and get back to you when I have
> received some smoke failures.
>
>
>
Thanks,
Yves

**Comment by thrig** [comment]
This is perl, v5.8.9 built for OpenBSD.amd64-openbsd
    % pm-version Test::More
    1.001014

Latest `Sereal`, `Time::Moment` via `cpan`. With `Data::Dumper::qquote` added, we see that the `$decoded->[$x]` are, uh, what they are:

    #   Failed test 'first element has right time'
    #   at t/530_sereal.t line 34.
    t/530_sereal....NOK 8/0#          got: '2012-12-24T15:30:45.123456789+01:00' 
    #     expected: '2012-12-24T15:30:45.123456789+01:00'
    # Got "Time::Moment=SCALAR(0x4a041309640)"
    t/530_sereal....NOK 9/0                                                      
    #   Failed test 'second element has right time'
    #   at t/530_sereal.t line 36.
    #          got: '2012-12-24T15:30:45.987654321+01:00'
    #     expected: '2012-12-24T15:30:45.987654321+01:00'
    # Got "Time::Moment=SCALAR(0x4a041309690)"

changing the `$decoded->[$x]` to be `$decoded->[$x]->to_string` causes the tests to pass. So this appears XS/stringify related. There's nothing obvious in the `perl510*delta.pod` as to stringification changes (besides UTF-8 handling fixes) that would indicate why stringification is failing. :/

(There's a `make` warning about `THX_sv_2moment` being defined but not used, but that looks unrelated to the `XS_Time_Moment_stringify` call.)

**Comment by chansen** [comment]
I have received a [pull request](https://github.com/chansen/p5-time-moment/pull/17) for Time::Moment, which suggest that the issue is related to a change in `Test::More` package.

**Comment by demerphq** [comment]
So can I resolve this ticket?

On 9 September 2015 at 13:22, Christian Hansen <notifications@github.com>
wrote:

> I have received a pull request
> <https://github.com/chansen/p5-time-moment/pull/17> for Time::Moment,
> which suggest that the issue is related to a change in Test::More package.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Sereal/Sereal/issues/98#issuecomment-138879833>.
>



-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by demerphq** [comment]
Resolving.
